export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: 'pao' | 'doces' | 'salgados' | 'bolos' | 'bebidas' | 'promocoes';
  rating: number;
  reviews: number;
  featured?: boolean;
  discount?: number;
}

export const products: Product[] = [
  // Pães
  {
    id: 'pao-frances',
    name: 'Pão Francês',
    description: 'Pão francês tradicional, crocante por fora e macio por dentro',
    price: 0.80,
    image: 'https://tse1.mm.bing.net/th/id/OIP.MLD2MrpkVsNg2fCCs60grwHaF7?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'pao',
    rating: 4.8,
    reviews: 324,
    featured: true,
  },
  {
    id: 'pao-integral',
    name: 'Pão Integral',
    description: 'Pão integral feito com farinha de trigo integral, rico em fibras',
    price: 2.50,
    image: 'https://tse1.mm.bing.net/th/id/OIP.XwgLz2qjqH08StGccBT-XgHaE8?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'pao',
    rating: 4.6,
    reviews: 156,
  },
  {
    id: 'pao-centeio',
    name: 'Pão de Centeio',
    description: 'Pão escuro e saudável com sementes de centeio',
    price: 3.00,
    image: 'https://tse3.mm.bing.net/th/id/OIP.uB81HE1OMImgICNr-DdR6wHaE7?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'pao',
    rating: 4.7,
    reviews: 89,
  },
  {
    id: 'pao-sourdough',
    name: 'Pão Sourdough',
    description: 'Pão artesanal com fermentação natural, sabor único e complexo',
    price: 5.50,
    image: 'https://img.freepik.com/fotos-premium/sourdough-e-um-pao-feito-de-fermentacao-natural-de-levedura-usando-farinha-de-trigo-salgada_454892-1826.jpg',
    category: 'pao',
    rating: 4.9,
    reviews: 267,
    featured: true,
  },

  // Doces
  {
    id: 'croissant-manteiga',
    name: 'Croissant de Manteiga',
    description: 'Croissant francês crocante, folhado e delicioso',
    price: 3.50,
    image: 'https://tse1.explicit.bing.net/th/id/OIP.tvKEcUYGe1s_O102_09avAHaE8?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'doces',
    rating: 4.9,
    reviews: 412,
    featured: true,
  },
  {
    id: 'croissant-chocolate',
    name: 'Croissant de Chocolate',
    description: 'Croissant folhado com chocolate belga premium',
    price: 4.00,
    image: 'https://tse4.mm.bing.net/th/id/OIP.C5-bTGUo2WYEKO1gHYmtKgHaEP?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'doces',
    rating: 4.8,
    reviews: 356,
  },
  {
    id: 'bolo-chocolate',
    name: 'Bolo de Chocolate',
    description: 'Bolo de chocolate caseiro, macio e saboroso',
    price: 8.50,
    image: 'https://tse1.mm.bing.net/th/id/OIP.uC50nZdfAD1Hm0YC-YZ2WwHaE8?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'bolos',
    rating: 4.7,
    reviews: 198,
  },
  {
    id: 'bolo-cenoura',
    name: 'Bolo de Cenoura',
    description: 'Bolo de cenoura com cobertura de chocolate',
    price: 7.50,
    image: 'https://tse3.mm.bing.net/th/id/OIP.V8loYj7flxXUdPvxyEBFkgHaE8?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'bolos',
    rating: 4.8,
    reviews: 234,
  },
  {
    id: 'brigadeiro',
    name: 'Brigadeiro Artesanal',
    description: 'Brigadeiro feito com chocolate belga e leite condensado',
    price: 1.50,
    image: 'https://tse1.mm.bing.net/th/id/OIP.xNlBdTkUNj9UHBO-OarSagHaEK?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'doces',
    rating: 4.9,
    reviews: 567,
    featured: true,
  },
  {
    id: 'torta-fruta',
    name: 'Torta de Frutas',
    description: 'Torta com frutas frescas e calda de morango',
    price: 12.00,
    image: 'https://tse4.mm.bing.net/th/id/OIP.iHlpVsaLpm-hNY4lZ2oSvQHaFE?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'bolos',
    rating: 4.9,
    reviews: 145,
  },

  // Salgados
  {
    id: 'pastel-carne',
    name: 'Pastel de Carne',
    description: 'Pastel crocante com recheio de carne moída',
    price: 2.50,
    image: 'https://static.vecteezy.com/system/resources/previews/024/582/252/non_2x/homemade-taco-with-grilled-steak-fresh-vegetables-and-spicy-sauce-generated-by-ai-free-photo.jpg',
    category: 'salgados',
    rating: 4.7,
    reviews: 289,
  },
  {
    id: 'pastel-queijo',
    name: 'Pastel de Queijo',
    description: 'Pastel com queijo derretido e crocante',
    price: 2.50,
    image: 'https://i.pinimg.com/736x/13/d0/71/13d0719573c87cd7cd766646b1fd894a.jpg',
    category: 'salgados',
    rating: 4.6,
    reviews: 201,
  },
  {
    id: 'coxinha-frango',
    name: 'Coxinha de Frango',
    description: 'Coxinha crocante com frango desfiado',
    price: 2.00,
    image: 'https://tse1.explicit.bing.net/th/id/OIP.C33eIMASnBT46uw0QfiMRgHaE8?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'salgados',
    rating: 4.8,
    reviews: 445,
    featured: true,
  },
  {
    id: 'broa-queijo',
    name: 'Broa de Queijo',
    description: 'Broa salgada com queijo parmesão',
    price: 1.80,
    image: 'https://guiadacozinha.com.br/wp-content/uploads/2011/01/broadefubacomqueijo.webp',
    category: 'salgados',
    rating: 4.7,
    reviews: 178,
  },
  {
    id: 'esfiha-carne',
    name: 'Esfiha de Carne',
    description: 'Esfiha aberta com carne temperada',
    price: 3.00,
    image: 'https://th.bing.com/th/id/R.6723982a6b25dbeebcaf59513c3fe3d5?rik=w3EPbCmlClvhbA&riu=http%3a%2f%2fthumbor.guiame.com.br%2funsafe%2fsmart%2fmedia.guiame.com.br%2farchives%2f2014%2f10%2f31%2f3471086826-esfiha-fechada-de-carne.jpg&ehk=VCv0oUx1QNTACjT7%2f%2bQYmpkNBSwuFt5J67j9IAFAa1A%3d&risl=&pid=ImgRaw&r=0',
    category: 'salgados',
    rating: 4.8,
    reviews: 312,
  },

  // Bebidas
  {
    id: 'cafe-expresso',
    name: 'Café Expresso',
    description: 'Café expresso feito com grãos premium',
    price: 3.50,
    image: 'https://cdn.warenvergleich.de/v2/sites/7/espresso-beliebt-scaled-1.jpeg?d=1660x1106&q=70',
    category: 'bebidas',
    rating: 4.8,
    reviews: 523,
  },
  {
    id: 'cafe-cappuccino',
    name: 'Cappuccino',
    description: 'Cappuccino cremoso com espuma de leite',
    price: 4.50,
    image: 'https://tse1.mm.bing.net/th/id/OIP.o7dj03FWHpEELz_eH7xlqwHaEK?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'bebidas',
    rating: 4.9,
    reviews: 612,
    featured: true,
  },
  {
    id: 'cafe-latte',
    name: 'Café Latte',
    description: 'Café latte suave com leite vaporizado',
    price: 4.00,
    image: 'https://tse3.mm.bing.net/th/id/OIP.wcsbyeq3bRnCZrmLR4rhogHaEK?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'bebidas',
    rating: 4.8,
    reviews: 456,
  },
  {
    id: 'suco-natural',
    name: 'Suco Natural',
    description: 'Suco natural de frutas frescas',
    price: 5.00,
    image: 'https://tse4.mm.bing.net/th/id/OIP.O0nxQUgeL0caGtys06SUbwHaE8?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'bebidas',
    rating: 4.7,
    reviews: 234,
  },
  {
    id: 'cha-quente',
    name: 'Chá Quente',
    description: 'Chá quente de várias opções',
    price: 3.00,
    image: 'https://image.freepik.com/fotos-gratis/xicara-de-cha-quente-com-limao-e-gengibre_73558-230.jpg',
    category: 'bebidas',
    rating: 4.6,
    reviews: 145,
  },

  // Promoções
  {
    id: 'combo-cafe-pao',
    name: 'Combo Café + Pão',
    description: 'Café expresso + Pão francês (3 unidades)',
    price: 4.50,
    image: 'https://tse2.mm.bing.net/th/id/OIP.7iMo7yh6SQZZSWo2GaSgTQHaE7?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'promocoes',
    rating: 4.9,
    reviews: 678,
    featured: true,
    discount: 15,
  },
  {
    id: 'combo-cafe-doce',
    name: 'Combo Café + Doce',
    description: 'Cappuccino + Croissant de Chocolate',
    price: 7.50,
    image: 'https://tse3.mm.bing.net/th/id/OIP.eBDJyTxom3T_0Xi8WPm89QHaE7?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'promocoes',
    rating: 4.8,
    reviews: 456,
    discount: 10,
  },
  {
    id: 'combo-salgados',
    name: 'Combo Salgados',
    description: 'Pastel + Coxinha + Broa (3 unidades de cada)',
    price: 12.00,
    image: 'https://tse4.mm.bing.net/th/id/OIP.lDmdnv4d8Cim3gvB-WFE1wHaE8?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'promocoes',
    rating: 4.7,
    reviews: 234,
    discount: 20,
  },
];

export const categories = [
  { id: 'pao', name: 'Pães', icon: '🥖' },
  { id: 'doces', name: 'Doces', icon: '🍰' },
  { id: 'salgados', name: 'Salgados', icon: '🥐' },
  { id: 'bolos', name: 'Bolos', icon: '🎂' },
  { id: 'bebidas', name: 'Bebidas', icon: '☕' },
  { id: 'promocoes', name: 'Promoções', icon: '🎉' },
];
