export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: 'pao' | 'doces' | 'salgados' | 'bolos' | 'bebidas' | 'promocoes';
  rating: number;
  reviews: number;
  featured?: boolean;
  discount?: number;
}

export const products: Product[] = [
  // Pães
  {
    id: 'pao-frances',
    name: 'Pão Francês',
    description: 'Pão francês tradicional, crocante por fora e macio por dentro',
    price: 0.80,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'pao',
    rating: 4.8,
    reviews: 324,
    featured: true,
  },
  {
    id: 'pao-integral',
    name: 'Pão Integral',
    description: 'Pão integral feito com farinha de trigo integral, rico em fibras',
    price: 2.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'pao',
    rating: 4.6,
    reviews: 156,
  },
  {
    id: 'pao-centeio',
    name: 'Pão de Centeio',
    description: 'Pão escuro e saudável com sementes de centeio',
    price: 3.00,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'pao',
    rating: 4.7,
    reviews: 89,
  },
  {
    id: 'pao-sourdough',
    name: 'Pão Sourdough',
    description: 'Pão artesanal com fermentação natural, sabor único e complexo',
    price: 5.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/hero-padaria-2a3UHStXVwCDSVHPqA8wLa.webp',
    category: 'pao',
    rating: 4.9,
    reviews: 267,
    featured: true,
  },

  // Doces
  {
    id: 'croissant-manteiga',
    name: 'Croissant de Manteiga',
    description: 'Croissant francês crocante, folhado e delicioso',
    price: 3.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'doces',
    rating: 4.9,
    reviews: 412,
    featured: true,
  },
  {
    id: 'croissant-chocolate',
    name: 'Croissant de Chocolate',
    description: 'Croissant folhado com chocolate belga premium',
    price: 4.00,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'doces',
    rating: 4.8,
    reviews: 356,
  },
  {
    id: 'bolo-chocolate',
    name: 'Bolo de Chocolate',
    description: 'Bolo de chocolate caseiro, macio e saboroso',
    price: 8.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'bolos',
    rating: 4.7,
    reviews: 198,
  },
  {
    id: 'bolo-cenoura',
    name: 'Bolo de Cenoura',
    description: 'Bolo de cenoura com cobertura de chocolate',
    price: 7.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'bolos',
    rating: 4.8,
    reviews: 234,
  },
  {
    id: 'brigadeiro',
    name: 'Brigadeiro Artesanal',
    description: 'Brigadeiro feito com chocolate belga e leite condensado',
    price: 1.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'doces',
    rating: 4.9,
    reviews: 567,
    featured: true,
  },
  {
    id: 'torta-fruta',
    name: 'Torta de Frutas',
    description: 'Torta com frutas frescas e calda de morango',
    price: 12.00,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'bolos',
    rating: 4.9,
    reviews: 145,
  },

  // Salgados
  {
    id: 'pastel-carne',
    name: 'Pastel de Carne',
    description: 'Pastel crocante com recheio de carne moída',
    price: 2.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'salgados',
    rating: 4.7,
    reviews: 289,
  },
  {
    id: 'pastel-queijo',
    name: 'Pastel de Queijo',
    description: 'Pastel com queijo derretido e crocante',
    price: 2.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'salgados',
    rating: 4.6,
    reviews: 201,
  },
  {
    id: 'coxinha-frango',
    name: 'Coxinha de Frango',
    description: 'Coxinha crocante com frango desfiado',
    price: 2.00,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'salgados',
    rating: 4.8,
    reviews: 445,
    featured: true,
  },
  {
    id: 'broa-queijo',
    name: 'Broa de Queijo',
    description: 'Broa salgada com queijo parmesão',
    price: 1.80,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'salgados',
    rating: 4.7,
    reviews: 178,
  },
  {
    id: 'esfiha-carne',
    name: 'Esfiha de Carne',
    description: 'Esfiha aberta com carne temperada',
    price: 3.00,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'salgados',
    rating: 4.8,
    reviews: 312,
  },

  // Bebidas
  {
    id: 'cafe-expresso',
    name: 'Café Expresso',
    description: 'Café expresso feito com grãos premium',
    price: 3.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/cafe-quente-4QtBzMWe8DLfsdtvwPE37A.webp',
    category: 'bebidas',
    rating: 4.8,
    reviews: 523,
  },
  {
    id: 'cafe-cappuccino',
    name: 'Cappuccino',
    description: 'Cappuccino cremoso com espuma de leite',
    price: 4.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/cafe-quente-4QtBzMWe8DLfsdtvwPE37A.webp',
    category: 'bebidas',
    rating: 4.9,
    reviews: 612,
    featured: true,
  },
  {
    id: 'cafe-latte',
    name: 'Café Latte',
    description: 'Café latte suave com leite vaporizado',
    price: 4.00,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/cafe-quente-4QtBzMWe8DLfsdtvwPE37A.webp',
    category: 'bebidas',
    rating: 4.8,
    reviews: 456,
  },
  {
    id: 'suco-natural',
    name: 'Suco Natural',
    description: 'Suco natural de frutas frescas',
    price: 5.00,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/cafe-quente-4QtBzMWe8DLfsdtvwPE37A.webp',
    category: 'bebidas',
    rating: 4.7,
    reviews: 234,
  },
  {
    id: 'cha-quente',
    name: 'Chá Quente',
    description: 'Chá quente de várias opções',
    price: 3.00,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/cafe-quente-4QtBzMWe8DLfsdtvwPE37A.webp',
    category: 'bebidas',
    rating: 4.6,
    reviews: 145,
  },

  // Promoções
  {
    id: 'combo-cafe-pao',
    name: 'Combo Café + Pão',
    description: 'Café expresso + Pão francês (3 unidades)',
    price: 4.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/cafe-quente-4QtBzMWe8DLfsdtvwPE37A.webp',
    category: 'promocoes',
    rating: 4.9,
    reviews: 678,
    featured: true,
    discount: 15,
  },
  {
    id: 'combo-cafe-doce',
    name: 'Combo Café + Doce',
    description: 'Cappuccino + Croissant de Chocolate',
    price: 7.50,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/cafe-quente-4QtBzMWe8DLfsdtvwPE37A.webp',
    category: 'promocoes',
    rating: 4.8,
    reviews: 456,
    discount: 10,
  },
  {
    id: 'combo-salgados',
    name: 'Combo Salgados',
    description: 'Pastel + Coxinha + Broa (3 unidades de cada)',
    price: 12.00,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663397842081/ahwD2ddPqsnE4wP56Q3ptx/produtos-padaria-GpbdAhrpAEoim6gwZgty3S.webp',
    category: 'promocoes',
    rating: 4.7,
    reviews: 234,
    discount: 20,
  },
];

export const categories = [
  { id: 'pao', name: 'Pães', icon: '🥖' },
  { id: 'doces', name: 'Doces', icon: '🍰' },
  { id: 'salgados', name: 'Salgados', icon: '🥐' },
  { id: 'bolos', name: 'Bolos', icon: '🎂' },
  { id: 'bebidas', name: 'Bebidas', icon: '☕' },
  { id: 'promocoes', name: 'Promoções', icon: '🎉' },
];
